# Generated by Django 4.2.11 on 2026-06-22 22:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name="Date d'arrivée")),
                ('check_out_date', models.DateField(verbose_name='Date de départ')),
                ('adults', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Nombre d'adultes")),
                ('children', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('checked_in', 'Arrivé'), ('checked_out', 'Parti'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix total (FCFA)')),
                ('special_requests', models.TextField(blank=True, help_text='Allergies, préférences, accessibilité...', verbose_name='Demandes spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.room', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (FCFA)')),
                ('method', models.CharField(choices=[('card', 'Carte bancaire'), ('cash', 'Espèces'), ('transfer', 'Virement bancaire'), ('mobile', 'Mobile Money')], default='card', max_length=20, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='ID de transaction')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée réelle")),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Heure de départ réelle')),
                ('notes', models.TextField(blank=True, help_text='Observations du réceptionniste lors du check-in/check-out', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receptionist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_checkins', to=settings.AUTH_USER_MODEL, verbose_name='Réceptionniste')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_record', to='reservations.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Enregistrement Check-in/out',
                'verbose_name_plural': 'Enregistrements Check-in/out',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='reservation_checkout_after_checkin'),
        ),
    ]
