# Generated by Django 4.2.11 on 2026-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('card', 'Carte bancaire'), ('cash', 'Espèces'), ('transfer', 'Virement bancaire')], default='card', max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
