# Generated by Django 4.2.11 on 2026-06-22 22:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('max_occupancy', models.PositiveIntegerField(default=2, verbose_name='Capacité maximale (personnes)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de base par nuit (FCFA)')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='Ex: ["WiFi", "Climatisation", "TV", "Minibar"]', verbose_name='Commodités')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de chambre',
                'verbose_name_plural': 'Catégories de chambres',
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Haute saison, Noël & Nouvel An, Été', max_length=100, verbose_name='Nom de la saison')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix par nuit (FCFA)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='rooms.roomcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Tarif saisonnier',
                'verbose_name_plural': 'Tarifs saisonniers',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Ex: 101, A2, PH1', max_length=10, unique=True, verbose_name='Numéro de chambre')),
                ('floor', models.PositiveIntegerField(verbose_name='Étage')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupée'), ('maintenance', 'En maintenance'), ('cleaning', 'En nettoyage')], default='available', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, help_text='Informations spécifiques à cette chambre (vue mer, coin salon...)', verbose_name='Description spécifique')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Photo principale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active (visible aux clients)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['floor', 'number'],
            },
        ),
    ]
